/**
* Generated by mosn mecha
 */

package common

import (
	"mosn.io/api"
	"mosn.io/pkg/header"
)

type Header struct {
	header.BytesHeader
}

func (h *Header) Clone() api.HeaderMap {

	return &Header{BytesHeader: *h.BytesHeader.Clone()}
}

var _ api.HeaderMap = &Header{}

